# Generated by Django 5.2.5 on 2026-02-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('openapi_version', models.CharField(default='3.0.0', max_length=20)),
                ('content', models.JSONField(help_text='Swagger/OpenAPI JSON/YAML的解析内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_specs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_testing.apispecification')),
            ],
        ),
        migrations.CreateModel(
            name='APITestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('endpoint', '单接口'), ('scenario', '场景链路')], max_length=20)),
                ('request_data', models.JSONField(default=dict, help_text='包含headers, body, params等')),
                ('assertions', models.JSONField(default=list, help_text='断言规则列表')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(blank=True, help_text='关联的端点（端点类型用例适用）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.apiendpoint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='APITestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases', models.ManyToManyField(related_name='suites', to='api_testing.apitestcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_suites', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='APITestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testing.apitestsuite')),
            ],
        ),
    ]
