# Generated by Django 5.2.5 on 2026-02-28 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama'), ('qwen', 'Qwen'), ('custom', 'Custom')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_base', models.CharField(blank=True, max_length=255, null=True)),
                ('is_vision_model', models.BooleanField(default=False, help_text='是否为视觉大模型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('server_url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('db_type', models.CharField(choices=[('chromadb', 'ChromaDB'), ('milvus', 'Milvus')], max_length=20)),
                ('connection_kwargs', models.JSONField(default=dict, help_text='数据库连接参数配置')),
            ],
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_prompt', models.IntegerField(default=0)),
                ('tokens_completion', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.llmconfiguration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
