# Generated by Django 5.2.5 on 2026-02-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUITestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('steps', models.JSONField(default=list, help_text='包含 action, target, value 结构的操作步骤')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_test_cases', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MidSceneScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_content', models.TextField(help_text='MidScene 视觉/自然语言测试脚本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='midscene_script', to='web_testing.webuitestcase')),
            ],
        ),
        migrations.CreateModel(
            name='WebUITestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases', models.ManyToManyField(related_name='suites', to='web_testing.webuitestcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_test_suites', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WebUITestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20)),
                ('allure_report_url', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='web_testing.webuitestsuite')),
            ],
        ),
    ]
