# Generated by Django 5.2.5 on 2026-02-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webuitestcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_test_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webuitestcase',
            name='priority',
            field=models.CharField(choices=[('高', '高'), ('中', '中'), ('低', '低')], default='中', max_length=10),
        ),
        migrations.AddField(
            model_name='webuitestcase',
            name='test_type',
            field=models.CharField(choices=[('功能测试', '功能测试'), ('异常测试', '异常测试'), ('边界测试', '边界测试'), ('安全测试', '安全测试'), ('性能测试', '性能测试')], default='功能测试', max_length=20),
        ),
    ]
